version: '2'

services:
  bymeldingservice:
    image: bymdocker/bymeldingservice
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=localdocker
    links:
      - bymlocaldb
  autentiseringservice:
    image: bymdocker/autentiseringservice
    ports:
      - "5015:5015"
    environment:
      - ASPNETCORE_ENVIRONMENT=localdocker
    links:
      - bymlocaldb    
  bymlocaldb:
    image: bymdocker/postgresql-dev
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=developer2016