FROM node:7.1.0

# Create app directory
WORKDIR /app
COPY . /app

# Install app dependencies
RUN npm install
ENV TZ Europe/Oslo
RUN ln -fs /usr/share/zoneinfo/Europe/Oslo /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

EXPOSE 5006

CMD ["npm", "run", "build-and-run"]